import vertica_python

conn_info = {'host': 'localhost',
             'port': 5433,
             'user': 'dbadmin',
             'password': '',
             'database': 'docker',
             # autogenerated session label by default,
             'session_label': 'some_label',
             # default throw error on invalid UTF-8 results
             'unicode_error': 'strict',
             # SSL is disabled by default
             'ssl': False,
             # using server-side prepared statements is disabled by default
             'use_prepared_statements': False,
             # connection timeout is not enabled by default
             # 5 seconds timeout for a socket operation (Establishing a TCP connection or read/write operation)
             'connection_timeout': 5}

# simple connection, with manual close
connection = vertica_python.connect(**conn_info)
# do things
connection.close()

# using with for auto connection closing after usage
with vertica_python.connect(**conn_info) as conn:
      # do things
      cur = conn.cursor()
      cur.execute(r"COPY test_vert.STG_NEW_CAPACITIES(commodity,cause,region,country_or_teritory,company,site,plant_no,estimated_start_date,exp_ann_cap_change,total_annual, swing_capable) FROM local 'C:\Users\adyan.beltikov\Desktop\programs\Docker\csv\NEW_CAPACITIES.csv' PARSER fcsvparser() ABORT ON ERROR;")
